/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as ContributorsIndexRouteImport } from './routes/contributors/index'
import { Route as CategoriesIndexRouteImport } from './routes/categories/index'
import { Route as TagSlugRouteImport } from './routes/tag/$slug'
import { Route as PostSlugRouteImport } from './routes/post/$slug'
import { Route as DashboardProfileRouteImport } from './routes/dashboard/profile'
import { Route as DashboardAdminRouteImport } from './routes/dashboard/admin'
import { Route as AuthorAuthorIdRouteImport } from './routes/author/$authorId'
import { Route as DashboardPostNewRouteImport } from './routes/dashboard/post/new'
import { Route as DashboardPostIdEditRouteImport } from './routes/dashboard/post/$id/edit'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const ContributorsIndexRoute = ContributorsIndexRouteImport.update({
  id: '/contributors/',
  path: '/contributors/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesIndexRoute = CategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => rootRouteImport,
} as any)
const TagSlugRoute = TagSlugRouteImport.update({
  id: '/tag/$slug',
  path: '/tag/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PostSlugRoute = PostSlugRouteImport.update({
  id: '/post/$slug',
  path: '/post/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthorAuthorIdRoute = AuthorAuthorIdRouteImport.update({
  id: '/author/$authorId',
  path: '/author/$authorId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPostNewRoute = DashboardPostNewRouteImport.update({
  id: '/post/new',
  path: '/post/new',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPostIdEditRoute = DashboardPostIdEditRouteImport.update({
  id: '/post/$id/edit',
  path: '/post/$id/edit',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/changelog': typeof ChangelogRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/author/$authorId': typeof AuthorAuthorIdRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/post/$slug': typeof PostSlugRoute
  '/tag/$slug': typeof TagSlugRoute
  '/categories/': typeof CategoriesIndexRoute
  '/contributors/': typeof ContributorsIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/post/new': typeof DashboardPostNewRoute
  '/dashboard/post/$id/edit': typeof DashboardPostIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/changelog': typeof ChangelogRoute
  '/author/$authorId': typeof AuthorAuthorIdRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/post/$slug': typeof PostSlugRoute
  '/tag/$slug': typeof TagSlugRoute
  '/categories': typeof CategoriesIndexRoute
  '/contributors': typeof ContributorsIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/post/new': typeof DashboardPostNewRoute
  '/dashboard/post/$id/edit': typeof DashboardPostIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/changelog': typeof ChangelogRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/author/$authorId': typeof AuthorAuthorIdRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/post/$slug': typeof PostSlugRoute
  '/tag/$slug': typeof TagSlugRoute
  '/categories/': typeof CategoriesIndexRoute
  '/contributors/': typeof ContributorsIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/post/new': typeof DashboardPostNewRoute
  '/dashboard/post/$id/edit': typeof DashboardPostIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/changelog'
    | '/dashboard'
    | '/author/$authorId'
    | '/dashboard/admin'
    | '/dashboard/profile'
    | '/post/$slug'
    | '/tag/$slug'
    | '/categories/'
    | '/contributors/'
    | '/dashboard/'
    | '/dashboard/post/new'
    | '/dashboard/post/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/changelog'
    | '/author/$authorId'
    | '/dashboard/admin'
    | '/dashboard/profile'
    | '/post/$slug'
    | '/tag/$slug'
    | '/categories'
    | '/contributors'
    | '/dashboard'
    | '/dashboard/post/new'
    | '/dashboard/post/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/changelog'
    | '/dashboard'
    | '/author/$authorId'
    | '/dashboard/admin'
    | '/dashboard/profile'
    | '/post/$slug'
    | '/tag/$slug'
    | '/categories/'
    | '/contributors/'
    | '/dashboard/'
    | '/dashboard/post/new'
    | '/dashboard/post/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChangelogRoute: typeof ChangelogRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  AuthorAuthorIdRoute: typeof AuthorAuthorIdRoute
  PostSlugRoute: typeof PostSlugRoute
  TagSlugRoute: typeof TagSlugRoute
  CategoriesIndexRoute: typeof CategoriesIndexRoute
  ContributorsIndexRoute: typeof ContributorsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/contributors/': {
      id: '/contributors/'
      path: '/contributors'
      fullPath: '/contributors/'
      preLoaderRoute: typeof ContributorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/': {
      id: '/categories/'
      path: '/categories'
      fullPath: '/categories/'
      preLoaderRoute: typeof CategoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tag/$slug': {
      id: '/tag/$slug'
      path: '/tag/$slug'
      fullPath: '/tag/$slug'
      preLoaderRoute: typeof TagSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post/$slug': {
      id: '/post/$slug'
      path: '/post/$slug'
      fullPath: '/post/$slug'
      preLoaderRoute: typeof PostSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/author/$authorId': {
      id: '/author/$authorId'
      path: '/author/$authorId'
      fullPath: '/author/$authorId'
      preLoaderRoute: typeof AuthorAuthorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/post/new': {
      id: '/dashboard/post/new'
      path: '/post/new'
      fullPath: '/dashboard/post/new'
      preLoaderRoute: typeof DashboardPostNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/post/$id/edit': {
      id: '/dashboard/post/$id/edit'
      path: '/post/$id/edit'
      fullPath: '/dashboard/post/$id/edit'
      preLoaderRoute: typeof DashboardPostIdEditRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAdminRoute: typeof DashboardAdminRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardPostNewRoute: typeof DashboardPostNewRoute
  DashboardPostIdEditRoute: typeof DashboardPostIdEditRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAdminRoute: DashboardAdminRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardPostNewRoute: DashboardPostNewRoute,
  DashboardPostIdEditRoute: DashboardPostIdEditRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChangelogRoute: ChangelogRoute,
  DashboardRoute: DashboardRouteWithChildren,
  AuthorAuthorIdRoute: AuthorAuthorIdRoute,
  PostSlugRoute: PostSlugRoute,
  TagSlugRoute: TagSlugRoute,
  CategoriesIndexRoute: CategoriesIndexRoute,
  ContributorsIndexRoute: ContributorsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
